title: Christian Haro
description: WIP Portfolio
show_downloads: false
avatar: https://avatars2.githubusercontent.com/u/4326205?s=400&v=4

footer-links:
  linkedin: www.linkedin.com/in/christian-haro-50b017a1

google_analytics: UA-113621348-1
theme: jekyll-theme-minimal 
